version: "3.9"
services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6378"
    command: redis-server --port 6378

  database:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"